# Generated by Django 4.2.8 on 2023-12-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='id',
        ),
        migrations.AddField(
            model_name='customers',
            name='customer_id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
