# Generated by Django 4.2.8 on 2023-12-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0002_remove_customers_id_customers_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
