# Generated by Django 4.2.8 on 2023-12-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0002_alter_customers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
