# Generated by Django 4.2.8 on 2023-12-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0003_alter_customers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
