# Generated by Django 4.2.8 on 2024-02-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='pharmacy_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
