# Generated by Django 4.2.8 on 2024-02-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_pharmacy_pharmacy_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='pharmacy_logo',
            field=models.FileField(blank=True, default='null', null=True, upload_to=''),
        ),
    ]
